name: Continuous Release
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build-android:
    uses: ./.github/workflows/android.yml
    secrets: inherit
  build-linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit
  build-mac:
    uses: ./.github/workflows/mac.yml
    secrets: inherit
  build-windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  release:
    permissions:
      contents: write
    needs:
      - build-android
      - build-linux
      - build-mac
      - build-windows
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: asset-*
          merge-multiple: true

      - name: Run uploadtool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: 'true'
          UPLOADTOOL_BODY: |-
            ## Android

            Download `Labrador-<version>-release-signed.apk` for manual installation on Android 4.1 "Jelly Bean" or later (API Level 16).

            ## Linux (including Raspberry Pi)

            The packages below have been compiled for 64-bit distros.  If you're running 32-bit, please see the [build instructions](https://github.com/espotek-org/Labrador/wiki/Building-from-source).

            ### AppImage

            Download the `aarch64` AppImage for 64-bit ARM computers (e.g. Raspberry Pi), or the `x86_64` AppImage for 64-bit Intel/AMD computers.

            - First make the AppImage file executable by running `chmod +x Labrador-<version>-<arch>.AppImage`
            - Now you can run it just like any other program or script: `./Labrador-<version>-<arch>.AppImage`

            ### Debian package

            Download the `arm64` Debian package for 64-bit ARM computers (e.g. Raspberry Pi), or the `amd64` Debian package for 64-bit Intel/AMD computers.

            To install, run `sudo dpkg -i Labrador-<version>-<arch>.deb`.

            ## macOS

            Download `Labrador-<version>.dmg` for macOS 10.13 and later.
            If you are running an older version of macOS, please use the macOS Legacy build below.

            - Drag the Labrador app into `/Applications`
            - Right-click and Open the Labrador app in your `/Applications` directory (you need to right-click and open, you can't just double-click)
            - If you see a warning message, just press the `Open` button to continue
            - That's it, you're done!  From now on you can open by simply double-clicking as you would any other app

            ## Windows

            Download `Labrador-<version>-installer.exe` for Windows 7 or later (32-bit and 64-bit supported).
        run: |
          UPLOADTOOL_BODY="$(echo "$UPLOADTOOL_BODY" | jq -Rsa '.')"
          UPLOADTOOL_BODY="${UPLOADTOOL_BODY%\"}"
          UPLOADTOOL_BODY="${UPLOADTOOL_BODY#\"}"

          wget -N https://github.com/probonopd/uploadtool/raw/master/upload.sh
          chmod +x ./upload.sh
          find . -type f -not -path ./upload.sh -exec ./upload.sh {} +
