name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: true
      matrix:
        include:
          - QT_ARCH: 'win64_msvc2019_64'
            PLATFORM: 'x64'
            PLATFORM_ALT_NAME: 'x64'
            OUTPUT_BIN_DIR: 'bin64'
          - QT_ARCH: 'win32_msvc2019'
            PLATFORM: 'x86'
            PLATFORM_ALT_NAME: 'x86'
            OUTPUT_BIN_DIR: 'bin32'

    permissions:
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1) Install eigen
      - name: Install eigen
        shell: cmd
        run: |
          choco install eigen

      # 2) Install Qt (5.15.2) for the desired MSVC2019 architecture
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: '${{ matrix.QT_ARCH }}'

      # 3) Activate the MSVC 2019 environment
      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.PLATFORM }}

      # 4) Debug step: Confirm cl, nmake, qmake are found
      - name: Debug environment
        shell: cmd
        run: |
          echo "PATH=%PATH%"
          where cl
          where nmake
          where qmake

      # 5) Build Labrador
      - name: Build Labrador
        working-directory: Desktop_Interface
        shell: cmd
        run: |
          qmake CONFIG+=release INCLUDEPATH+="C:\ProgramData\chocolatey\lib\eigen\include\eigen3"
          nmake

      # 6) Post-build steps: windeployqt, copy fftw DLL, etc.
      - name: Post-build steps
        working-directory: Desktop_Interface
        shell: cmd
        run: |
          windeployqt bin\Labrador.exe
          xcopy /i /s /y "build_win\fftw\${{ matrix.PLATFORM_ALT_NAME }}"\libfftw3-3.dll bin
          del bin\vcredist*.exe
          del bin\*.pdb

      # 7) Upload artifact
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Labrador_${{ matrix.PLATFORM }}
          path: Desktop_Interface/bin

      # 8) Optional: Push result to Labrador-win-builder
      - name: Publish update to Labrador-win-builder
        if: success()
        shell: pwsh
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          OUTPUT_BIN_DIR: ${{ matrix.OUTPUT_BIN_DIR }}
        run: |
          mkdir C:\dev
          cd C:\dev
          git clone --depth 1 https://github.com/espotek-org/Labrador-win-builder
          cd Labrador-win-builder
          git config --global credential.helper store
          Add-Content "$env:USERPROFILE\.git-credentials" "https://$env:ACCESS_TOKEN:x-oauth-basic@github.com`n"
          git config --global user.email "admin@espotek.com"
          git config --global user.name "Chris Esposito"
          git checkout master
          xcopy /i /s /y "%GITHUB_WORKSPACE%\Desktop_Interface\bin" $env:OUTPUT_BIN_DIR
          git add $env:OUTPUT_BIN_DIR
          git commit -a -m "Automatic update from main Labrador repository"
          git push
